# Generated by Django 4.1.7 on 2023-05-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_picture', models.ImageField(upload_to='static/')),
                ('card_title', models.TextField()),
                ('card_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='fir_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fir_date', models.DateField()),
                ('fir_police_station', models.CharField(max_length=200)),
                ('fir_id', models.CharField(max_length=200)),
                ('fir_adhar', models.CharField(max_length=15)),
                ('fir_fullname', models.CharField(max_length=200)),
                ('fir_age', models.IntegerField()),
                ('fir_gender', models.CharField(max_length=200)),
                ('fir_phone', models.CharField(max_length=20)),
                ('fir_address', models.CharField(max_length=200)),
                ('fir_register_by', models.CharField(max_length=200)),
                ('fir_photo', models.ImageField(upload_to='static/')),
                ('fir_type', models.CharField(max_length=200)),
                ('fir_subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='greeting_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_photo', models.ImageField(upload_to='static/')),
                ('greeting_info', models.TextField()),
                ('greeting_name', models.CharField(max_length=50)),
                ('greeting_position', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=200)),
                ('comp_adhar', models.CharField(max_length=15)),
                ('comp_fullname', models.CharField(max_length=200)),
                ('comp_age', models.IntegerField()),
                ('comp_gender', models.CharField(max_length=200)),
                ('comp_phone', models.CharField(max_length=20)),
                ('comp_address', models.CharField(max_length=200)),
                ('comp_register_by', models.CharField(max_length=200)),
                ('comp_photo', models.ImageField(upload_to='static/')),
                ('comp_type', models.CharField(max_length=200)),
                ('comp_subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='policestationreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField()),
                ('st_pass', models.CharField(max_length=15)),
                ('station_name', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='printed_gallary1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_photo', models.ImageField(upload_to='static/')),
                ('printed_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='savepolicestationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=200)),
                ('st_id', models.TextField()),
                ('st_pass', models.TextField()),
                ('st_con_pass', models.TextField()),
                ('st_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='saveuserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_age', models.IntegerField()),
                ('user_add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='slidermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=200)),
                ('slider_headerline', models.CharField(max_length=200)),
                ('slider_details', models.CharField(max_length=200)),
                ('slider_image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='station_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=200)),
                ('st_id', models.CharField(max_length=200)),
                ('st_pass', models.CharField(max_length=200)),
                ('st_con_pass', models.CharField(max_length=200)),
                ('st_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=200)),
            ],
        ),
    ]
