# Generated by Django 4.1.7 on 2023-05-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_usercharcertificatedata1_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='insert_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_staff_adhar', models.CharField(max_length=100)),
                ('insert_staff_first_name', models.CharField(max_length=100)),
                ('insert_staff_last_name', models.CharField(max_length=100)),
                ('insert_staff_birth', models.DateField()),
                ('insert_staff_office_name', models.CharField(max_length=100)),
                ('insert_staff_mobile', models.CharField(max_length=100)),
                ('insert_staff_joning_date', models.CharField(max_length=100)),
                ('insert_staff_education', models.CharField(max_length=100)),
                ('insert_staff_address', models.CharField(max_length=300)),
                ('insert_staff_gender', models.CharField(max_length=100)),
                ('insert_staff_email', models.CharField(max_length=100)),
            ],
        ),
    ]
