# Generated by Django 4.1.7 on 2023-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_insert_staff_insert_staff_midd_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphtype',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
