# Generated by Django 4.1.7 on 2023-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0005_alter_graphtype_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='public_alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='static/')),
            ],
        ),
        migrations.AlterField(
            model_name='graphtype',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
