# Generated by Django 4.1.7 on 2023-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0006_public_alert_alter_graphtype_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='public_alert',
            new_name='PublicAlert',
        ),
    ]
