# Generated by Django 4.1.7 on 2023-05-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0007_rename_public_alert_publicalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecomplaint',
            name='comp_station',
            field=models.CharField(default=22, max_length=200),
            preserve_default=False,
        ),
    ]
