# Generated by Django 4.1.7 on 2023-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_onlinecomplaint_comp_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_name', models.CharField(max_length=100)),
                ('missing_description', models.CharField(max_length=500)),
                ('missing_adhar', models.CharField(max_length=200)),
                ('missing_phone', models.ImageField(upload_to='static/')),
                ('missing_address', models.CharField(max_length=200)),
            ],
        ),
    ]
